"""Data types for OpenNotebook."""

import hashlib
import json
import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Literal, Optional

# =============================================================================
# Artifact Types (Phase 4)
# =============================================================================


class ArtifactType(str, Enum):
    """Artifact type enumeration.

    Artifacts are structured outputs produced by the agent during task execution.
    """

    FILE = "file"  # PPT, Word, PDF, etc.
    CHART = "chart"  # ECharts, Plotly configuration
    CODE = "code"  # Code blocks
    TABLE = "table"  # Tabular data
    IMAGE = "image"  # Images
    MARKDOWN = "markdown"  # Markdown documents


@dataclass
class Artifact:
    """Agent-produced structured artifact.

    Artifacts represent concrete outputs from task execution, such as:
    - Generated files (documents, presentations)
    - Chart configurations for visualization
    - Code snippets
    - Structured data tables
    - Images or diagrams

    Attributes:
        id: Unique identifier for the artifact.
        type: Type of artifact (file, chart, code, etc.).
        title: Human-readable title.
        data: Content payload (type depends on artifact type).
        mime_type: Optional MIME type for binary content.
        url: Optional download/access URL.
        metadata: Additional metadata (source task, timestamps, etc.).
    """

    id: str
    type: ArtifactType
    title: str
    data: Any
    mime_type: Optional[str] = None
    url: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize artifact to dictionary.

        Returns:
            Dictionary representation of the artifact.
        """
        return {
            "id": self.id,
            "type": self.type.value if isinstance(self.type, ArtifactType) else self.type,
            "title": self.title,
            "data": self.data,
            "mime_type": self.mime_type,
            "url": self.url,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Artifact":
        """Create artifact from dictionary.

        Args:
            data: Dictionary with artifact data.

        Returns:
            Artifact instance.
        """
        artifact_type = data.get("type")
        if isinstance(artifact_type, str):
            artifact_type = ArtifactType(artifact_type)

        return cls(
            id=data["id"],
            type=artifact_type,
            title=data["title"],
            data=data.get("data"),
            mime_type=data.get("mime_type"),
            url=data.get("url"),
            metadata=data.get("metadata", {}),
        )


class TaskType(Enum):
    """Types of tasks that can be executed."""

    SYNTHESIZE = "synthesize"
    SEARCH = "search"
    ANALYZE = "analyze"
    GENERATE = "generate"


# =============================================================================
# DAG Execution Types (Phase 2)
# =============================================================================


class TaskStatus(Enum):
    """Status of a task node in the DAG."""

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"  # Skipped due to upstream failure


class TaskSource(str, Enum):
    """Origin of a task node.

    Attributes:
        RULE: Task was created by deterministic rule-based planning.
        LLM: Task was generated by the LLM.
        HYBRID: Task was created by rule + LLM enhancement.
    """

    RULE = "rule"
    LLM = "llm"
    HYBRID = "hybrid"


@dataclass
class Constraint:
    """Execution constraint for a task.

    Constraints define limits and requirements for task execution,
    such as timeouts, retry policies, or resource requirements.

    Attributes:
        type: Type of constraint ("timeout", "retry", "resource", "dependency").
        value: The constraint value (type depends on constraint type).
        source: Which planning stage added this constraint.
    """

    type: str  # "timeout", "retry", "resource", "dependency"
    value: Any
    source: str  # Which stage added this constraint

    def to_dict(self) -> Dict[str, Any]:
        """Serialize constraint to dictionary."""
        return {
            "type": self.type,
            "value": self.value,
            "source": self.source,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Constraint":
        """Create Constraint from dictionary."""
        return cls(
            type=data["type"],
            value=data["value"],
            source=data.get("source", "unknown"),
        )


@dataclass
class ReplanRecord:
    """Record of a replan event.

    Captures metadata about a replanning operation for debugging
    and analysis purposes.

    Attributes:
        timestamp: When the replan occurred.
        trigger: What triggered the replan ("checkpoint", "failure", "manual").
        trigger_task_id: ID of the task that triggered the replan.
        old_task_count: Number of tasks before replan.
        new_task_count: Number of tasks after replan.
        tasks_cancelled: List of task IDs that were cancelled.
        tasks_added: List of task IDs that were added.
        reason: Human-readable reason for the replan.
    """

    timestamp: datetime
    trigger: str  # "checkpoint", "failure", "manual"
    trigger_task_id: Optional[str]
    old_task_count: int
    new_task_count: int
    tasks_cancelled: List[str]
    tasks_added: List[str]
    reason: str

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "timestamp": self.timestamp.isoformat(),
            "trigger": self.trigger,
            "trigger_task_id": self.trigger_task_id,
            "old_task_count": self.old_task_count,
            "new_task_count": self.new_task_count,
            "tasks_cancelled": self.tasks_cancelled,
            "tasks_added": self.tasks_added,
            "reason": self.reason,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ReplanRecord":
        """Create ReplanRecord from dictionary."""
        timestamp = data.get("timestamp")
        if isinstance(timestamp, str):
            timestamp = datetime.fromisoformat(timestamp)
        elif timestamp is None:
            timestamp = datetime.now()

        return cls(
            timestamp=timestamp,
            trigger=data.get("trigger", "unknown"),
            trigger_task_id=data.get("trigger_task_id"),
            old_task_count=data.get("old_task_count", 0),
            new_task_count=data.get("new_task_count", 0),
            tasks_cancelled=data.get("tasks_cancelled", []),
            tasks_added=data.get("tasks_added", []),
            reason=data.get("reason", ""),
        )


@dataclass
class RetryLoopConfig:
    """Configuration for a retry loop in the DAG.

    Defines a verify-fix-retry loop pattern commonly used
    in test automation and self-healing workflows.

    Attributes:
        verify_task: Task ID of the verification step.
        fix_task: Task ID of the fix/repair step.
        max_attempts: Maximum total attempts (including initial).
        backoff_seconds: Delay between retries.
    """

    verify_task: str
    fix_task: str
    max_attempts: int = 3
    backoff_seconds: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dictionary."""
        return {
            "verify_task": self.verify_task,
            "fix_task": self.fix_task,
            "max_attempts": self.max_attempts,
            "backoff_seconds": self.backoff_seconds,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "RetryLoopConfig":
        """Create RetryLoopConfig from dictionary."""
        return cls(
            verify_task=data["verify_task"],
            fix_task=data["fix_task"],
            max_attempts=data.get("max_attempts", 3),
            backoff_seconds=data.get("backoff_seconds", 0.0),
        )


@dataclass
class TaskNode:
    """A node in the task DAG with dependencies.

    Attributes:
        id: Unique identifier for the task.
        skill: Name of the skill to execute.
        params: Parameters to pass to the skill.
        depends_on: List of task IDs this task depends on.
        status: Current execution status.
        result: Result from skill execution (if completed).
        error: Error message (if failed).
        started_at: When execution started.
        finished_at: When execution finished.
        is_checkpoint: Whether this task triggers re-plan evaluation.
        source: Origin of this task (rule, llm, or hybrid).
        confidence: Confidence score (0.0-1.0) for LLM-generated tasks.
        constraints: Execution constraints (timeout, retry, etc.).
        generation: Replan generation counter for ID conflict resolution.
    """

    id: str
    skill: str
    params: Dict[str, Any]
    depends_on: List[str] = field(default_factory=list)
    status: TaskStatus = TaskStatus.PENDING
    result: Optional[Any] = None
    error: Optional[str] = None
    started_at: Optional[datetime] = None
    finished_at: Optional[datetime] = None

    # Re-planning support
    is_checkpoint: bool = False  # Trigger re-plan when completed

    # NEW: Source tracking
    source: TaskSource = TaskSource.RULE
    """Origin of this task: rule-based, LLM-generated, or hybrid."""

    # NEW: Confidence score
    confidence: float = 1.0
    """
    Confidence in task correctness (0.0-1.0).
    - Rule tasks: 1.0 (deterministic)
    - LLM tasks: varies based on model confidence
    - Used for prioritization and fallback decisions
    """

    # NEW: Execution constraints
    constraints: List[Constraint] = field(default_factory=list)
    """
    Constraints on task execution:
    - timeout: max execution time
    - retry: retry policy
    - resource: resource requirements
    - dependency: additional runtime dependencies
    """

    # NEW: Replan generation
    generation: int = 0
    """
    Replan generation counter.
    Incremented each time this task ID is reused in a replan.
    Used for ID conflict resolution and tracing.
    """

    # NEW: Failure handling fields (ADR-007)
    on_failure: Optional[str] = None
    """
    Task ID to execute when this task fails.
    If set, instead of marking downstream as SKIPPED,
    execute the failure handler task first.
    Example: on_failure="t4_fix"
    """

    retry_target: Optional[str] = None
    """
    Task ID to retry after this (fix) task completes successfully.
    Used for fix-and-retry patterns.
    Example: retry_target="t3_verify"
    """

    max_retries: int = 0
    """
    Maximum number of retry attempts for this task.
    0 = no retry (default behavior).
    Works with on_failure to implement retry loops.
    """

    retry_count: int = 0
    """
    Current retry attempt counter (runtime state).
    Incremented each time the task is retried.
    """

    inactive: bool = False
    """
    Whether this task is initially inactive.
    Inactive tasks are not scheduled until explicitly activated
    (e.g., via on_failure trigger).
    """

    # Cached signature
    _signature: Optional[str] = field(default=None, repr=False)

    @property
    def duration_ms(self) -> Optional[int]:
        """Calculate execution duration in milliseconds."""
        if self.started_at and self.finished_at:
            delta = self.finished_at - self.started_at
            return int(delta.total_seconds() * 1000)
        return None

    def get_signature(self) -> str:
        """Get or compute semantic signature for task comparison.

        The signature is a hash of (skill, params) that can be used
        to compare tasks across replans for meaningful change detection.

        Returns:
            A 16-character hex string signature.
        """
        if self._signature is None:
            content = json.dumps(
                {
                    "skill": self.skill,
                    "params": self.params,
                },
                sort_keys=True,
            )
            self._signature = hashlib.sha256(content.encode()).hexdigest()[:16]
        return self._signature

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "id": self.id,
            "skill": self.skill,
            "params": self.params,
            "depends_on": self.depends_on,
            "status": self.status.value,
            "result": self.result,
            "error": self.error,
            "started_at": self.started_at.isoformat() if self.started_at else None,
            "finished_at": self.finished_at.isoformat() if self.finished_at else None,
            "duration_ms": self.duration_ms,
            "is_checkpoint": self.is_checkpoint,
            # New fields
            "source": self.source.value if isinstance(self.source, TaskSource) else self.source,
            "confidence": self.confidence,
            "constraints": [c.to_dict() for c in self.constraints],
            "generation": self.generation,
            # Retry/failure handling fields (ADR-007)
            "on_failure": self.on_failure,
            "retry_target": self.retry_target,
            "max_retries": self.max_retries,
            "retry_count": self.retry_count,
            "inactive": self.inactive,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "TaskNode":
        """Create TaskNode from dictionary.

        Args:
            data: Dictionary with node data.

        Returns:
            TaskNode instance.
        """
        started_at = None
        if data.get("started_at"):
            started_at = datetime.fromisoformat(data["started_at"])

        finished_at = None
        if data.get("finished_at"):
            finished_at = datetime.fromisoformat(data["finished_at"])

        # Parse source (backward compatible)
        source = data.get("source", "rule")
        if isinstance(source, str):
            try:
                source = TaskSource(source)
            except ValueError:
                source = TaskSource.RULE

        # Parse constraints (backward compatible)
        constraints_data = data.get("constraints", [])
        constraints = [Constraint.from_dict(c) for c in constraints_data]

        return cls(
            id=data["id"],
            skill=data["skill"],
            params=data.get("params", {}),
            depends_on=data.get("depends_on", []),
            status=TaskStatus(data.get("status", "pending")),
            result=data.get("result"),
            error=data.get("error"),
            started_at=started_at,
            finished_at=finished_at,
            is_checkpoint=data.get("is_checkpoint", False),
            # New fields with defaults for backward compatibility
            source=source,
            confidence=data.get("confidence", 1.0),
            constraints=constraints,
            generation=data.get("generation", 0),
            # Retry/failure handling fields (ADR-007)
            on_failure=data.get("on_failure"),
            retry_target=data.get("retry_target"),
            max_retries=data.get("max_retries", 0),
            retry_count=data.get("retry_count", 0),
            inactive=data.get("inactive", False),
        )


@dataclass
class TaskDAG:
    """Directed Acyclic Graph of tasks with dependencies.

    Attributes:
        id: Unique identifier for the DAG.
        goal: User's original goal/request.
        nodes: Dictionary mapping task ID to TaskNode.
        created_at: When the DAG was created.
        replan_history: History of replans applied to this DAG.
        retry_loops: Retry loop configurations in this DAG.
    """

    id: str
    goal: str
    nodes: Dict[str, TaskNode]
    created_at: datetime = field(default_factory=datetime.now)

    # NEW: Replan history
    replan_history: List[ReplanRecord] = field(default_factory=list)
    """History of replans applied to this DAG."""

    # NEW: Retry loops (ADR-007)
    retry_loops: List[RetryLoopConfig] = field(default_factory=list)
    """Retry loop configurations in this DAG."""

    @classmethod
    def create(cls, goal: str, tasks: List[Dict[str, Any]]) -> "TaskDAG":
        """Create DAG from task definitions.

        Args:
            goal: User's original goal
            tasks: List of task dicts with id, skill, params, depends_on

        Returns:
            TaskDAG instance
        """
        dag_id = f"dag_{uuid.uuid4().hex[:8]}"
        nodes = {}

        for task in tasks:
            # Parse source if provided
            source = task.get("source", "rule")
            if isinstance(source, str):
                try:
                    source = TaskSource(source)
                except ValueError:
                    source = TaskSource.RULE

            # Parse constraints if provided
            constraints_data = task.get("constraints", [])
            constraints = [
                Constraint.from_dict(c) if isinstance(c, dict) else c for c in constraints_data
            ]

            node = TaskNode(
                id=task["id"],
                skill=task["skill"],
                params=task.get("params", {}),
                depends_on=task.get("depends_on", []),
                is_checkpoint=task.get("is_checkpoint", False),
                source=source,
                confidence=task.get("confidence", 1.0),
                constraints=constraints,
                generation=task.get("generation", 0),
                # Retry/failure handling fields (ADR-007)
                on_failure=task.get("on_failure"),
                retry_target=task.get("retry_target"),
                max_retries=task.get("max_retries", 0),
                retry_count=task.get("retry_count", 0),
                inactive=task.get("inactive", False),
            )
            nodes[node.id] = node

        return cls(id=dag_id, goal=goal, nodes=nodes)

    @classmethod
    def create_simple(cls, skill: str, params: Dict[str, Any]) -> "TaskDAG":
        """Create a simple single-task DAG (for direct/fallback mode)."""
        task_id = f"task_{uuid.uuid4().hex[:8]}"
        return cls.create(
            goal="direct_response", tasks=[{"id": task_id, "skill": skill, "params": params}]
        )

    def get_ready_tasks(self) -> List[TaskNode]:
        """Get all tasks whose dependencies are satisfied.

        Returns:
            List of TaskNode that can be executed now
        """
        ready = []
        for node in self.nodes.values():
            if node.status != TaskStatus.PENDING:
                continue

            # Skip inactive tasks (only executed via on_failure trigger)
            if node.inactive:
                continue

            # Check all dependencies are completed
            deps_satisfied = all(
                self.nodes[dep_id].status == TaskStatus.COMPLETED
                for dep_id in node.depends_on
                if dep_id in self.nodes
            )

            if deps_satisfied:
                ready.append(node)

        return ready

    def is_completed(self) -> bool:
        """Check if all tasks are in terminal state."""
        return all(
            node.status in (TaskStatus.COMPLETED, TaskStatus.FAILED, TaskStatus.SKIPPED)
            for node in self.nodes.values()
        )

    def get_results(self) -> Dict[str, Any]:
        """Collect results from all completed tasks."""
        return {
            node_id: node.result
            for node_id, node in self.nodes.items()
            if node.status == TaskStatus.COMPLETED
        }

    def get_errors(self) -> Dict[str, str]:
        """Collect errors from all failed tasks."""
        return {
            node_id: node.error or "Unknown error"
            for node_id, node in self.nodes.items()
            if node.status == TaskStatus.FAILED
        }

    def get_downstream_tasks(self, task_id: str) -> List[TaskNode]:
        """Get all tasks that depend on the given task."""
        return [node for node in self.nodes.values() if task_id in node.depends_on]

    def mark_downstream_skipped(self, failed_task_id: str) -> None:
        """Mark all downstream tasks as SKIPPED due to upstream failure."""
        to_skip = [failed_task_id]
        visited = set()

        while to_skip:
            current = to_skip.pop(0)
            if current in visited:
                continue
            visited.add(current)

            for node in self.get_downstream_tasks(current):
                if node.status == TaskStatus.PENDING:
                    node.status = TaskStatus.SKIPPED
                    node.error = f"Skipped: upstream task '{current}' failed"
                    to_skip.append(node.id)

    def get_llm_tasks(self) -> List[TaskNode]:
        """Get all LLM-generated tasks.

        Returns:
            List of TaskNode where source is LLM.
        """
        return [n for n in self.nodes.values() if n.source == TaskSource.LLM]

    def get_rule_tasks(self) -> List[TaskNode]:
        """Get all rule-based tasks.

        Returns:
            List of TaskNode where source is RULE.
        """
        return [n for n in self.nodes.values() if n.source == TaskSource.RULE]

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for serialization."""
        return {
            "id": self.id,
            "goal": self.goal,
            "nodes": {k: v.to_dict() for k, v in self.nodes.items()},
            "created_at": self.created_at.isoformat(),
            # New fields
            "replan_history": [r.to_dict() for r in self.replan_history],
            "retry_loops": [r.to_dict() for r in self.retry_loops],
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "TaskDAG":
        """Create TaskDAG from dictionary.

        Args:
            data: Dictionary with DAG data.

        Returns:
            TaskDAG instance with restored nodes and state.
        """
        # Parse created_at
        created_at = data.get("created_at")
        if isinstance(created_at, str):
            created_at = datetime.fromisoformat(created_at)
        elif created_at is None:
            created_at = datetime.now()

        # Restore nodes
        nodes = {}
        nodes_data = data.get("nodes", {})
        for node_id, node_data in nodes_data.items():
            nodes[node_id] = TaskNode.from_dict(node_data)

        # Restore replan history (backward compatible)
        replan_history_data = data.get("replan_history", [])
        replan_history = [ReplanRecord.from_dict(r) for r in replan_history_data]

        # Restore retry loops (backward compatible)
        retry_loops_data = data.get("retry_loops", [])
        retry_loops = [RetryLoopConfig.from_dict(r) for r in retry_loops_data]

        return cls(
            id=data["id"],
            goal=data.get("goal", ""),
            nodes=nodes,
            created_at=created_at,
            replan_history=replan_history,
            retry_loops=retry_loops,
        )

    @property
    def completed_count(self) -> int:
        """Count of completed nodes."""
        return sum(1 for node in self.nodes.values() if node.status == TaskStatus.COMPLETED)

    @property
    def pending_count(self) -> int:
        """Count of pending nodes."""
        return sum(1 for node in self.nodes.values() if node.status == TaskStatus.PENDING)


@dataclass
class RuntimeConfig:
    """Configuration for the async runtime."""

    default_timeout: float = 30.0  # Single task timeout in seconds
    max_retries: int = 2  # Max retry attempts
    retry_delay: float = 1.0  # Delay between retries
    max_concurrent: int = 10  # Max concurrent tasks


@dataclass
class ExecutionStats:
    """Statistics from DAG execution."""

    total_tasks: int
    completed: int
    failed: int
    skipped: int
    total_duration_ms: int
    parallel_efficiency: float = 0.0  # actual_time / serial_time

    def to_dict(self) -> Dict[str, Any]:
        return {
            "total_tasks": self.total_tasks,
            "completed": self.completed,
            "failed": self.failed,
            "skipped": self.skipped,
            "total_duration_ms": self.total_duration_ms,
            "parallel_efficiency": self.parallel_efficiency,
        }


@dataclass
class ExecutionResult:
    """Result of DAG execution."""

    dag_id: str
    status: Literal["success", "partial", "failed"]
    results: Dict[str, Any]
    errors: Dict[str, str]
    duration_ms: int
    stats: ExecutionStats

    def to_dict(self) -> Dict[str, Any]:
        return {
            "dag_id": self.dag_id,
            "status": self.status,
            "results": self.results,
            "errors": self.errors,
            "duration_ms": self.duration_ms,
            "stats": self.stats.to_dict(),
        }


@dataclass
class Task:
    """A single executable task."""

    id: str
    type: TaskType
    skill: str
    params: dict
    result: Optional[Any] = None
    error: Optional[str] = None

    def to_dict(self) -> dict:
        """Convert task to dictionary."""
        return {
            "id": self.id,
            "type": self.type.value,
            "skill": self.skill,
            "params": self.params,
            "result": self.result,
            "error": self.error,
        }


@dataclass
class Plan:
    """Execution plan containing tasks or direct response."""

    mode: Literal["direct", "multi_step"]
    tasks: List[Task]
    direct_response: Optional[str] = None

    @classmethod
    def direct(cls, response: str) -> "Plan":
        """Create a direct response plan (no skill execution needed)."""
        return cls(mode="direct", tasks=[], direct_response=response)

    @classmethod
    def multi_step(cls, tasks: List[Task]) -> "Plan":
        """Create a multi-step plan with tasks to execute."""
        return cls(mode="multi_step", tasks=tasks)

    def is_direct(self) -> bool:
        """Check if this is a direct response plan."""
        return self.mode == "direct"


@dataclass
class AgentResponse:
    """Response from the code agent.

    The primary response object returned by CodeAgent.run() and run_stream().

    Attributes:
        text: Main text response to the user.
        error: Error message if execution failed.
        artifacts: List of structured artifacts produced during execution.
        suggestions: List of suggested follow-up actions/questions.
        dag: Optional TaskDAG reference for inspection.
        memory_stats: Optional memory usage statistics.
    """

    text: str
    error: Optional[str] = None
    artifacts: List[Artifact] = field(default_factory=list)
    suggestions: List[str] = field(default_factory=list)
    dag: Optional["TaskDAG"] = None
    memory_stats: Optional[Dict[str, Any]] = None

    def is_error(self) -> bool:
        """Check if this response contains an error."""
        return self.error is not None

    def has_artifacts(self) -> bool:
        """Check if this response contains artifacts."""
        return len(self.artifacts) > 0

    def get_artifacts_by_type(self, artifact_type: ArtifactType) -> List[Artifact]:
        """Get artifacts filtered by type.

        Args:
            artifact_type: Type of artifacts to retrieve.

        Returns:
            List of matching artifacts.
        """
        return [a for a in self.artifacts if a.type == artifact_type]

    def to_dict(self) -> Dict[str, Any]:
        """Serialize response to dictionary.

        Returns:
            Dictionary representation of the response.
        """
        return {
            "text": self.text,
            "error": self.error,
            "artifacts": [a.to_dict() for a in self.artifacts],
            "suggestions": self.suggestions,
            "dag": self.dag.to_dict() if self.dag else None,
            "memory_stats": self.memory_stats,
        }


# Backward compatibility alias
NotebookResponse = AgentResponse
